import type { Metadata } from "next";
import localFont from 'next/font/local'

import "./globals.css";
import { Header } from "@/components/header/header";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Imobiliaria Episum",
  description: "Generated by create next app",
};

const lufga = localFont({
  variable: "--font-lufga",
  src: [
    {
      path: "./fonts/lufga/LufgaBlack.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/lufga/LufgaRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/lufga/LufgaMedium.ttf",
      weight: "500",
    }, {
      path: "./fonts/lufga/LufgaBold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/lufga/LufgaLight.ttf",
      weight: "300",
    },
    {
      path: "./fonts/lufga/LufgaSemiBold.ttf",
      weight: "600",
    }, {
      path: "./fonts/lufga/LufgaExtraBold.ttf",
      weight: "800",
    },
    {
      path: "./fonts/lufga/LufgaExtraLight.ttf",
      weight: "200",
    }
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">

      <body
        className={`${lufga.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
